Simple Linear Regression

In [3]:
import numpy as np
from sklearn.linear_model import LinearRegression

variables:

  1 Independent
  
  2 Dependent

In [5]:
x = np.array([25,35,45,55,65,75])
y = np.array([5,20,14,32,22,38])

In [6]:
print(x)
print(y)

[25 35 45 55 65 75]
[ 5 20 14 32 22 38]


1.the input x and output y
2. reshape() on x because the array is required to be two dimentional

In [7]:
x = x.reshape((-1,1))

In [10]:
print(x)
x.shape

[[25]
 [35]
 [45]
 [55]
 [65]
 [75]]


(6, 1)

# create a model and fit it

In [12]:
model = LinearRegression()

In [13]:
model.fit(x,y)

LinearRegression()

Once your model fitted you can get the result  to check whether the model works satisfactorily and interpret it

In [14]:
r_sq_score = model.score(x,y)
print("coefficient of determination:",r_sq_score)

coefficient of determination: 0.7158756137479542


In [15]:
print("intercept:",model . intercept_)

intercept: -5.166666666666668


In [17]:
print("slope:",model.coef_)

slope: [0.54]


In [18]:
y_pred = model.predict(x)

In [19]:
print("actual values",y)
print("predicted response:", y_pred)

actual values [ 5 20 14 32 22 38]
predicted response: [ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]
